pruebacyc/apps/principal/urls.py
from django.conf.urls import url,include
from .views import menu,mapa,editarPerfil,coords_save,coords_obtener,coords_eliminar,index,index2,coords_save2

urlpatterns = [
    url(r'^$', menu, name='menu'),
    url(r'^mapeo$', mapa, name='mapeo'),
    url(r'^mapa/$', index, name='index'),
    url(r'^editarPerfil(?P<user_id>\d+)/$', editarPerfil, name='editar'),
    url(r'^coords/save$', coords_save, name='coords_save'),
    url(r'^coords/save2$', coords_save2, name='coords_save2'),
    url(r'^coords/obtener$', coords_obtener, name='coords_obtener'),
    url(r'^coords/eliminar$', coords_eliminar, name='coords_eliminar'),
	url(r'^viaje$', index2, name='index2'),
    
]

pruebacyc/pruebacyc/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from apps.conductor.views import registrarCuenta
from apps.principal.views import change_password
from apps.core.views import index,login
from apps.cliente.views import registrarCliente
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^registrar', registrarCuenta, name='registrar'),
    url(r'^registroCliente', registrarCliente, name='registroCliente'),
    url(r'^principal/', include(('apps.principal.urls','principal'),namespace='principal')),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^cambiaPASS/', change_password, name='cambiaPASS'),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pruebacyc/apps/cliente/models.py
from django.db import models

# Create your models here.

class Canal(models.Model):
    Canales = (
        ('Casa', 'Interno'),
        ('depa', 'Externo'),
        ('ajja', 'Go'),
    )
    tipoCanal = models.CharField(max_length=15, choices = Canales)
    def __str__(self):
        return self.tipoCanal
class FichaCliente(models.Model):
    rut     = models.CharField(max_length=9, blank=False, primary_key = True)
    pNombre = models.CharField(max_length=30)
    sNombre = models.CharField(max_length=30)
    apPaterno = models.CharField(max_length=30)
    apMaterno = models.CharField(max_length=30)
    direccion = models.CharField(max_length=30)
    fNacimiento = models.DateField()
    email = models.EmailField(max_length=254)
    telefono = models.CharField(max_length=9)
    Centro = models.ForeignKey(Canal, on_delete=models.CASCADE)
    def __str__(self):
        return self.rut + ' ' + self.pNombre + ' ' + self.sNombre + ' ' + self.apPaterno + ' ' + self.apMaterno + ' ' + self.direccion 

pruebacyc/apps/principal/models.py
from django.db import models

class Ubicacion(models.Model):
    lat = models.DecimalField(max_digits=50, decimal_places=20)
    lng = models.DecimalField(max_digits=50, decimal_places=20)
    fecha = models.DateField(auto_now_add=True)
    hora = models.TimeField(auto_now_add=True)

class UbicacionFinal(models.Model):
	lat = models.DecimalField(max_digits=50, decimal_places=20)
	lng = models.DecimalField(max_digits=50, decimal_places=20)
	fecha = models.DateField(auto_now_add=True)
	hora = models.TimeField(auto_now_add=True)
# Create your models here.

pruebacyc/apps/principal/forms.py
from django import forms
from .models import Ubicacion,UbicacionFinal

class UbicacionForm(forms.ModelForm):
    class Meta:
        model = Ubicacion
        fields = '__all__'

class UbicacionFinalForm(forms.ModelForm):
    class Meta:
        model = UbicacionFinal
        fields = '__all__'

pruebacyc/apps/principal/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from django.contrib import messages
from apps.conductor.models import FichaConductor
from django.contrib.auth.decorators import login_required
from apps.conductor.forms import formConductor2
 
import json
 
from django.template import RequestContext
from django.utils.timesince import timesince
from .models import Ubicacion
from .forms import UbicacionForm, UbicacionFinalForm
# Create your views here.


@login_required
def menu(request):
    us = request.user
    Conductor = FichaConductor.objects.filter(Usuario_id=us.id)
    return render(request,'Menu/principal.html',{'Conductor':Conductor})

@login_required
def mapa(request):
    form = UbicacionForm()
    return  render(request,'Menu/mapa.html', {'form':form})

@login_required
def editarPerfil(request,user_id):
    Conductor = FichaConductor.objects.get(Usuario_id = user_id)
    if request.method == 'GET':
        form = formConductor2(instance=Conductor)
    else:
        form = formConductor2(request.POST, instance=Conductor)
        if form.is_valid():
            form.save()
        return redirect('principal:menu')
    return  render(request,'Menu/editarPerfil.html',{'form':form})

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('index')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'registration/cambiaPass.html', {
        'form': form
    })

def index(request):
    form = UbicacionForm()
    ubicaciones = Ubicacion.objects.all().order_by('fecha')
 
    return render('mapa.html', {'form':form,'ubicaciones':ubicaciones}, RequestContext(request))


def index2(request):
    form = UbicacionFinalForm()

    return render(request,'Menu/mapa2.html', {'form':form}, RequestContext(request))
 
def coords_obtener(request):
 
    ubicacion = Ubicacion.objects.get(id=request.POST['value'])
 
    return HttpResponse(json.dumps({'lat': ubicacion.lat, 'lng':ubicacion.lng}))
 
 
 
def coords_eliminar(request):
 
    #obtenemos la id de ubicacion
    id = request.POST['value']
 
    #eliminamos la ubicacion
    Ubicacion.objects.filter(id=id).delete()
 
    #obtenemos todos los objetos en un html
    data = getHTML()
 
    #retornamos la respuesta para mostrarlo
    return HttpResponse(json.dumps({'ok': True, 'msg': data}))
 
 
#metodo para obtener el html que lista los objetos

 
 
def coords_save(request):
 
    if request.is_ajax():
 
        formUb = UbicacionForm(request.POST)
 
        if formUb.is_valid():
 
            formUb.save()
            
 
            return HttpResponse(json.dumps({'ok': True, 'msg': 'Ok'}))
        else:
            return HttpResponse(json.dumps({'ok': False, 'msg': 'Debes llenar todos los campos'}))


 
def coords_save(request):
 
    if request.is_ajax():
 
        formUb = UbicacionForm(request.POST)
 
        if formUb.is_valid():
 
            formUb.save()
            
 
            return HttpResponse(json.dumps({'ok': True, 'msg': 'Ok'}))
        else:
            return HttpResponse(json.dumps({'ok': False, 'msg': 'Debes llenar todos los campos'}))


def coords_save2(request):
 
    if request.is_ajax():
 
        formUb = UbicacionFinalForm(request.POST)
 
        if formUb.is_valid():
 
            formUb.save()
            
 
            return HttpResponse(json.dumps({'ok': True, 'msg': 'Ok'}))
        else:
            return HttpResponse(json.dumps({'ok': False, 'msg': 'Debes llenar todos los campos'}))

pruebacyc/templates/Menu/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Roboto:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="shortcut icon" href="#" type="image/x-icon">
    <title>Menu conductor CyC | {% block title %}{% endblock title %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo2.0.png' %}">
    
      
</head>
<body>
    <style>
        body,html
        {
            height: 100%;
        }
            a img:hover
            {
                opacity: 0.2;
            }
            .container-fluid {
               background-image: url("{% static 'img/background.jpg' %}") ;
               opacity:0.8;
              min-height: 100%;
    
            }
            .social 
            {
                color:#45A2C1;
            }
            .socialFace:hover
            {
                color: blue;
            }
            .socialTwitter:hover
            {
                color: cadetblue;
            }
            .socialInsta:hover
            {
                color: pink;
            }
            .socialMail:hover
            {
                color: red;
            }
            
    </style>
            <nav class="navbar navbar-expand-lg navbar-light" style="background: #0B4050;opacity:0.9;">
                    <a class="navbar-brand btn-outline-light"  href="{% url 'index' %}"><img class="img-fluid" src="{% static 'img/logo2.0.png' %}" width="50" height="50"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarText">
                      <ul class="navbar-nav m-auto">
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'principal:menu' %}" style="color:white"><i class="fas fa-home mr-1" style='color:#45A2C1'></i>Inicio</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'principal:mapeo' %}" style="color:white"><i class="fas fa-car mr-1"style='color:#45A2C1'></i>Mapa interactivo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" style="color:white"><i class="fas fa-chart-line mr-1"style='color:#45A2C1'></i>Consultar reportes</a>
                        </li>
                        {% if request.user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="#" style="color:white"><i class="fas fa-users mr-1"style='color:#45A2C1'></i>Gestionar cuentas</a>
                        </li>
                        {% endif %}

                      </ul>
                      <div class="dropdown open mt-2 mr-2">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                              {{user}}
                            </button>
                        <div class="dropdown-menu" aria-labelledby="triggerId">
                          <a class="dropdown-item" href="{% url 'principal:editar' user.id %}">Ver perfil</a>
                          <a class="dropdown-item" href="{% url 'cambiaPASS' %}">Cambiar contraseña</a>
                        </div>
                      </div>
                      <a name="" id="" class="btn btn-outline-danger text-center mr-2 mt-2" href="{% url 'logout' %}" role="button"><i  style="background:white;"></i>Salir</a>
                    </div>
                  </nav>    
                  <div>
                    {% block inicio %} 
                    {% endblock inicio %}
                    {% block arrendar %}
                    {% endblock arrendar %}
                  </div>  
                    
                    
        
        
         <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <footer class="footer" >
        <footer class="footer "style="background: #0B4050;opacity:0.9;">
            <div class=" text-center center-block" >
                 <a href="#"><i  class="socialFace fab fa-facebook fa-3x social" ></i></a>
                    <a href="#"><i class="socialTwitter fab fa-twitter fa-3x social"></i></a>
                    <a href="#"><i class="socialInsta fab fa-instagram fa-3x social"></i></a>
                    <a href="#"><i class="socialMail fa fa-envelope-square fa-3x social"></i></a>
                    <p style="color:white;font-weight: bolder ">© 2019 CyC </p>
                   
        </div>
     </footer>
</body>
</html>

pruebacyc/templates/Menu/editarPerfil.html
{% extends 'Menu/base.html' %}
{% block title %}Perfil{% endblock title %}
{% block arrendar %}
<style>
.container-fluid
{
    background-image: none;
}
</style>
<div class="container-fluid  ">
    <h2 class="mt-2">Info de la cuenta</h2>
    <form method="POST" enctype='multipart/form-data' class="text-end justify-content-center row"style="background-color: white;padding: 30px 0">
        {% csrf_token %}
                   {{form.rut.as_hidden}}
                   <div class="col-6 text-left">
                    <label for="id_pNombre">Primer nombre</label>
                    {{form.pNombre}}
                    <label for="id_sNombre"> Segundo nombre</label>
                    {{form.sNombre}}
                    <label for="id_apPaterno">Apellido paterno</label>
                    {{form.apPaterno}}
                   </div>
                   <div class="col-6">
                    <label for="id_apMaterno">Apellido Materno</label>
                    {{form.apMaterno}}
                    <label for="id_direccion">Dirección</label>
                    {{form.direccion}}
                    <label for="id_fNacimiento">Fecha de nacimiento</label>
                    {{form.fNacimiento}}
                    <label for="id_email">Dirección</label>
                    {{form.email}} 
                    <label for="id_telefono">Telefono</label>
                    {{form.telefono}} 
                   </div>
                   {{form.licencia.as_hidden}}
                   {{form.Vehiculo.as_hidden}}
                   {{form.Usuario.as_hidden}}      
            <div class="form-group col-12 col-md-6 justify-content-center mt-5">
                <input class="btn btn-block btn-outline-success p-3" value="Guardar cambios" type="submit">
            </div>
        </form>
{% endblock arrendar %}

pruebacyc/templates/Menu/mapa.html
{% extends 'Menu/base.html' %}
{% block title %}Mapa{% endblock title %}
{% block arrendar %}
<style>
    #mapa
    {
        height: 350px;
        width: 100%;
    }
</style>
    <h1>VIAJE</h1>
    <div id="mapa" class="capas"></div>
    <div id="datos" class="capas">
            <div id="form">
                <form method="post" id="form_coords">{% csrf_token %}
                    {{ form.as_p }}
                    <p>
                        <input type="submit" onclick="window.location.href = 'viaje';" id="guardar" value="Iniciar Viaje">
                    </p>
                </form>
            </div>
           
        </div>
<script>
    function initMap()
    {
        var options = {
            zoom:16,
            center:{lat:-33.453728,lng:-70.525542}
        }
        var map = new
        google.maps.Map(document.getElementById('mapa'),options);

        //marcador
        var marker = new google.maps.Marker({
            position:{lat:-33.453728,lng:-70.525542},
            map:map,
            icon:'../static/img/iconBICI.png'
        });
        var informacion = new google.maps.InfoWindow({
            content:'<a name="" id="id_BICI" class="btn btn-primary" href="http://127.0.0.1:8000/principal/bicis"  role="button">Ver bicicletas</a>'
        });
        marker.addListener('click',function(){
            informacion.open(map,marker);
        });
        
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDAh-eWM4l_Da6RZPHS1TMuUl5yt2MPPwQ&callback=initMap"
    async defer></script>

{% endblock arrendar %}
    

pruebacyc/templates/Menu/mapa2.html
{% extends 'Menu/base.html' %}
{% block title %}Mapa{% endblock title %}
{% block arrendar %}
<style>
    #mapa
    {
        height: 350px;
        width: 100%;
    }
</style>
    <h1>Planificación</h1>
    <div id="mapa" class="capas"></div>
    <div id="datos" class="capas">
            <div id="form">
                <form method="post" id="form_coords2">{% csrf_token %}
                    {{ form.as_p }}
                    <p>
                        <input type="submit" id="guardar" value="Terminar Viaje">
                    </p>
                </form>
            </div>
           
        </div>
<script>
    function initMap()
    {
        var options = {
            zoom:16,
            center:{lat:-33.453728,lng:-70.525542}
        }
        var map = new
        google.maps.Map(document.getElementById('mapa'),options);

        //marcador
        var marker = new google.maps.Marker({
            position:{lat:-33.453728,lng:-70.525542},
            map:map,
            icon:'../static/img/iconBICI.png'
        });
        var informacion = new google.maps.InfoWindow({
            content:'<a name="" id="id_BICI" class="btn btn-primary" href="http://127.0.0.1:8000/principal/bicis"  role="button">Ver bicicletas</a>'
        });
        marker.addListener('click',function(){
            informacion.open(map,marker);
        });
        
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDAh-eWM4l_Da6RZPHS1TMuUl5yt2MPPwQ&callback=initMap"
    async defer></script>

{% endblock arrendar %}
    

pruebacyc/templates/Menu/principal.html
{% extends 'Menu/base.html' %}
{% block title %}Inicio{% endblock title %}
{% block inicio %}
<style>
</style>
<div class="jumbotron container h-75 w-75 mt-5">
  <h1 style="font-weight: bolder;font-size: 30px">¡ Bienvenido de vuelta !</h1>
  <hr class="my-2">
  <p class="lead">Conductor:</p>
  {% for g in Conductor  %}
    {{g.pNombre}} {{g.apPaterno}} 
  {% endfor %}    
  <hr style="margin: 0px 0px 30px 0px">
    <p class="lead">
       <a name="" id="" class="btn btn-outline-info text-center mr-2 mt-2" href="{% url 'principal:editar' user.id %}" role="button"><i class="fas fa-edit mr-2" style="font-size: 30px"></i>Editar perfil</a>
    </p>
</div>
{% endblock inicio %}
    